version: "3"
services:
  app:
    build: .
    restart: always
    depends_on:
      - localstack
      - mocked-analytics
      - localstack-test
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command:
      - "./scripts/wait-for-it.sh"
      - "localstack:4569"
      - "--"
      - "pipenv"
      - "run"
      - "gunicorn"
      - "-b 0.0.0.0:8000"
      - "-w 4"
      - "--reload"
      - "app:app"
    networks:
      analytics-event-processer-network:

  localstack:
    image: localstack/localstack:latest
    container_name: analytics-event-processer-localstack
    environment:
      - SERVICES=dynamodb:4569
      - DEFAULT_REGION=eu-central-1
      - HOSTNAME=analytics-event-processer-localstack
    ports:
      - "4569:4569"
    networks:
      analytics-event-processer-network:

  localstack-test:
    image: localstack/localstack:latest
    container_name: analytics-event-processer-localstack-test
    environment:
      - SERVICES=dynamodb:4569
      - DEFAULT_REGION=eu-central-1
      - HOSTNAME=analytics-event-processer-localstack-test
    networks:
      analytics-event-processer-network:
  mocked-analytics:
    image: hashicorp/http-echo
    container_name: mocked-analytics
    command:
      - "-text"
      - "hello"
    networks:
      analytics-event-processer-network:

networks:
  analytics-event-processer-network:
